version: "3.7"

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build:
      args:
        USER_ID: 1001
        GROUP_ID: 1001
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
volumes:
  db:
    driver: local