version: "3.7"

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
#      - "8443:443"
    volumes:
      - ./:/var/www
#    networks:
#        - internal
    depends_on:
      - php-fpm
  php-fpm:
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      #XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=Docker"
#    networks:
#        - internal
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8084:80"
    environment:
      - PMA_HOST=${DB_CONNECTION}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
volumes:
  db:
    driver: local
#networks:
#    internal:
#        driver: bridge
#        ipam:
#            driver: default
#            config:
#                - subnet: 192.168.220.0/28
